# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wd2DjikpuKAr3LXOqt2hJgmJYEKptxxH
"""

from sentence_transformers import SentenceTransformer, util
import torch

# Load embedding model
embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# Knowledge base (can expand later)
knowledge_base = [
    "The capital of India is New Delhi.",
    "Insulin is a hormone produced by the pancreas.",
    "The Earth revolves around the Sun.",
    "Water boils at 100 degrees Celsius.",
    "Python is a popular programming language.",
    "Gravity was discovered by Isaac Newton.",
    "The largest planet in the solar system is Jupiter.",
    "The speed of light is approximately 3 x 10^8 meters per second."
]

# Precompute embeddings
kb_embeddings = embedder.encode(knowledge_base, convert_to_tensor=True)


def retrieve_top_k(question, k=3):
    q_emb = embedder.encode(question, convert_to_tensor=True)
    scores = util.cos_sim(q_emb, kb_embeddings)[0]

    top_k = torch.topk(scores, k)
    indices = top_k.indices

    references = [knowledge_base[i] for i in indices]
    ref_scores = [scores[i].item() for i in indices]

    return references, ref_scores


def compute_similarity(answer, references):
    ans_emb = embedder.encode(answer, convert_to_tensor=True)
    ref_embs = embedder.encode(references, convert_to_tensor=True)

    scores = util.cos_sim(ans_emb, ref_embs)[0]

    return float(torch.max(scores))  # best match

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch

# Determine device once
device = "cuda:0" if torch.cuda.is_available() else "cpu"

# Load tokenizer and model directly
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")
model.to(device)


def generate_answer(question, context):
    context_text = " ".join(context)

    prompt = f"""
    Use the following context to answer the question.
    If the answer is not in the context, say 'I am not certain'.

    Context:
    {context_text}

    Question: {question}
    """

    # Encode the prompt
    input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to(device)

    # Generate output
    outputs = model.generate(
        input_ids,
        max_new_tokens=60,
        do_sample=False
    )

    # Decode and return the generated text
    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return generated_text.strip()


def run_pipeline(question):
    # Step 1: Retrieve top-k references
    references, ref_scores = retrieve_top_k(question)

    # Step 2: Generate answer using context
    answer = generate_answer(question, references)

    # Step 3: Evaluate
    similarity_score = compute_similarity(answer, references)

    # Step 4: Decision logic
    if similarity_score < 0.3:
        label = "Low"
        hallucination = True
    elif similarity_score < 0.6:
        label = "Medium"
        hallucination = False
    else:
        label = "High"
        hallucination = False

    return {
        "question": question,
        "answer": answer,
        "references": references,
        "score": similarity_score,
        "confidence": label,
        "is_hallucination": hallucination
    }

